name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ] 
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: 
          echo "BASE_URL=https://login.salesforce.com/" >> .env
          echo "USER_NAME=divi@sfdcpsvpec2025.com" >> .env
          echo "PASS_WORD=123456789d" >> .env
          echo "HOME_URL=https://psvpec9-dev-ed.develop.lightning.force.com/lightning/setup/SetupOneHome/home" >> .env
          echo "SKYFLEET_HOME=https://psvpec9-dev-ed.develop.lightning.force.com/lightning/n/standard-ApprovalsHome " >> .env
          
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
